name: Build LogFileWatcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore LogFileWatcher/LogFileWatcher.csproj
    - name: Build project
      run: dotnet build -c Release --no-restore LogFileWatcher/LogFileWatcher.csproj
    - name: Publish project
      run: dotnet publish --no-restore --no-build LogFileWatcher/LogFileWatcher.csproj -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o published

