name: Build LogFileWatcher

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64 LogFileWatcher/LogFileWatcher.csproj
    - name: Build project
      run: dotnet build --no-restore -r linux-x64 -c Release LogFileWatcher/LogFileWatcher.csproj
    - name: Publish project
      run: dotnet publish --no-restore --no-build -r linux-x64 -c Release LogFileWatcher/LogFileWatcher.csproj -p:PublishSingleFile=true --self-contained true -o published
    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        path: published
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "published/*"